fos_user:
#    prefix: '/ems-admin'
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'
ems_core:
    resource: '@EMSCoreBundle/Controller/'
    prefix: '/ems-admin'
    type:     annotation
emsco:
    prefix: '/ems-admin'
    resource: '@EMSCoreBundle/Resources/config/routing/all.xml'
